default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tism_development
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: tism_test
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
