# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.4.3'

gem 'carrierwave'
gem 'devise'
gem 'dotenv-rails'
gem 'graphql'
gem 'httparty'
gem 'jbuilder'
gem 'kaminari'
gem 'mini_magick'
gem 'nokogiri'
gem 'os'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rails'
gem 'ransack'
gem 'redis'
gem 'ruby-lsp'
gem 'sass-rails'
gem 'sidekiq'
gem 'solargraph'
gem 'turbolinks'
#gem 'webpacker'
gem 'rack-cors'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'rails-controller-testing'
gem 'rails-i18n'
gem 'active_model_serializers', '~> 0.10.0'
gem 'active_storage_validations'

group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen'
  gem 'rubocop'
  gem 'spring'
  gem 'web-console'
  gem 'rubocop-rails-omakase'
end

group :test do
  gem 'capybara'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'simplecov'
end
