databases:
  - name: tism-postgres
    databaseName: tism_production
    user: tism_user

services:
  - type: web
    name: tism-backend
    runtime: ruby
    buildCommand: "bundle config set frozen false && bundle install"
    startCommand: "bundle exec rails db:migrate RAILS_ENV=production && bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tism-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4